server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: 고객
          uri: http://localhost:8082
          predicates:
            - Path=/customers/**, 
        - id: 주문
          uri: http://localhost:8083
          predicates:
            - Path=/orders/**, /stores/**, /payments/**, 
        - id: 배달
          uri: http://localhost:8084
          predicates:
            - Path=/deliveries/**, /riders/**, 
        - id: 알림
          uri: http://localhost:8085
          predicates:
            - Path=/notifications/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: 고객
          uri: http://고객:8080
          predicates:
            - Path=/customers/**, 
        - id: 주문
          uri: http://주문:8080
          predicates:
            - Path=/orders/**, /stores/**, /payments/**, 
        - id: 배달
          uri: http://배달:8080
          predicates:
            - Path=/deliveries/**, /riders/**, 
        - id: 알림
          uri: http://알림:8080
          predicates:
            - Path=/notifications/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
